name: CI

on:
  push:
  pull_request:
  release:
    types:
      - created

jobs:
  build-ubuntu:    
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
    - uses: actions/checkout@v2
      with:
        path: vcpkg-robotraconteur
    - uses: actions/checkout@v2
      with:
        path: vcpkg
        repository: microsoft/vcpkg
    - name: apt update
      run: sudo apt update
    - name: apt
      run: >
        sudo apt install zip unzip build-essential pkg-config -qq
    - name: bootstrap vcpkg
      run: ./bootstrap-vcpkg.sh
      working-directory: vcpkg
    - name: build robotraconteur
      run: ./vcpkg install --overlay-ports=../vcpkg-robotraconteur/ports robotraconteur
      working-directory: vcpkg
  build-win:
    runs-on: windows-2016
    steps:
    - uses: actions/checkout@v2
      with:
        path: vcpkg-robotraconteur
    - uses: actions/checkout@v2
      with:
        path: vcpkg
        repository: microsoft/vcpkg
    - name: bootstrap vcpkg
      run: bootstrap-vcpkg
      working-directory: vcpkg
    - name: build robotraconteur
      run: vcpkg install --triplet x64-windows --overlay-ports=../vcpkg-robotraconteur/ports robotraconteur
      working-directory: vcpkg
  build-osx:    
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
      with:
        path: vcpkg-robotraconteur
    - uses: actions/checkout@v2
      with:
        path: vcpkg
        repository: microsoft/vcpkg
    - name: bootstrap vcpkg
      run: ./bootstrap-vcpkg.sh
      working-directory: vcpkg
    - name: build robotraconteur
      run: ./vcpkg install --overlay-ports=../vcpkg-robotraconteur/ports robotraconteur
      working-directory: vcpkg